
### get
GET http://localhost:3001/api/persons

### delete
DELETE http://localhost:3001/api/persons/612e00911df644c5a515de3c

### post 
POST http://localhost:3001/api/persons
content-type:application/json

{
"name":"laja",
"number":"07063235116"
}


### put
      PUT http://localhost:3001/api/persons/612e01fc43336ec7d7b43257
      content-type:application/json

      {
        "name":"Musa Muhammad",
        "number":"07963235226"
      }